#!/usr/bin/bash

# -s n show template n
# -t n use  template n (dafaults to 1)
# file path (the first argument)

TEMPLATE_DIR="$HOME/.local/texinit/"

TEMPLATE=NULL
TO="out.tex"

CHECK_FILE_RETURN=false
ARG_T=false
ARG_S=false
ASK_OWRT=false
FIRST_ONE=true


function check_file() {
	if [ -a $TO ] ; then
		while true; do
			read -p "this would overwrite a file, proceed? [y/N]" yn
			case $yn in
	    			[Yy]* )
	        			CHECK_FILE_RETURN=false
	        			exit;;
	    			[Nn]* )
	        			CHECK_FILE_RETURN=true
	        			exit;;
	    			*) echo "invalid answer."
            		esac
        	done	 
    	fi
    	CHECK_FILE_RETURN=false
}    


if [ ! -d $TEMPLATE_DIR ] ; then
    	echo "creating $TEMPLATE_DIR ..."
    	mkdir -p $TEMPLATE_DIR
fi

for arg in $@
do
    	if [ $FIRST_ONE ] ; then
        	if [ -a arg ] ; then
			FILE_NAME=arg
			continue
        	else
			echo "file not found or not provided or not accessible, defaulting to out.tex"
        	fi
        	FIRST_ONE=false
    	fi
    	if [ ARG_T ] ; then
        	if [ -a "$TEMPLATE_DIR/template$arg" ] ; then
			TEMPLATE="$TEMPLATE_DIR/template$arg"
        	else
			echo "template not found, using default template"
        	fi
        	ARG_T=false
        	continue
    	fi
    	if [ ARG_S ] ; then
        	if [ -a "$TEMPLATE_DIR/template$arg" ] ; then
			cat "$TEMPLATE_DIR/template$arg"
        	else
			echo "template not found in $TEMPLATE_DIR"
        	fi
        	ARG_S=false
        	continue
    	fi  
	case arg in
        	"--help" | "-h")
			echo "not yet implemented"
			break;;
        	"--template" | "-t")
			ARG_T=true
			break;;
        	"--show" | "-s")
			ARG_S=true
			break;;
        	"--no-ask" | "-n")
			ASK_OWRT=true
			break;;
        	*)
			echo "invalid option, type --help or -h for help"
			break;;
	esac
done    

if [ ! $ASK_OWRT ] ; then
    	check_file
fi    

if [ $ASK_OWRT -o $CHECK_FILE_RETURN ] ; then
    	if [ -n "$TEMPLATE" ] ; then
        	echo "\documentclass[12pt]{article}" > $TO
        	echo "\begin{document}" >> $TO
        	echo "" >> $TO
        	echo "\end{document}" >> $TO
    	else
        	cp "$TEMPLATE" "$TO"
    	fi
else
    	exit
fi    


